ARG MICROMAMBA_VERSION=2.6.2

FROM rust:1.82-bookworm AS build
WORKDIR /src
COPY biohub-rs/Cargo.toml biohub-rs/Cargo.lock ./
COPY biohub-rs/src ./src
RUN cargo build --locked --release

FROM mambaorg/micromamba:${MICROMAMBA_VERSION}
ARG ENVIRONMENT
LABEL org.opencontainers.image.title="BioHub domain environment"
LABEL org.opencontainers.image.source="https://github.com/Wzhennan-icmm/biohub-github-release"
COPY containers/environments /tmp/biohub-environments
RUN test -n "${ENVIRONMENT}" \
    && test -f "/tmp/biohub-environments/${ENVIRONMENT}.yaml" \
    && micromamba install --yes --name base --file "/tmp/biohub-environments/${ENVIRONMENT}.yaml" \
    && micromamba clean --all --yes
USER root
COPY --from=build /src/target/release/biohub /usr/local/bin/biohub
COPY recipes /usr/local/share/biohub/recipes
COPY r /usr/local/share/biohub/r
COPY examples /usr/local/share/biohub/examples
COPY LICENSE NOTICE /usr/local/share/doc/biohub/
ENV PATH="/opt/conda/bin:${PATH}"
USER ${MAMBA_USER}
ENTRYPOINT ["biohub"]
CMD ["--help"]
